# Generated by Django 5.2.12 on 2026-04-12 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrimaryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('plan', models.CharField(default='WE Gold 100', max_length=50)),
                ('renewal_day', models.CharField(default='Day 1', max_length=20)),
                ('total_data', models.PositiveIntegerField(default=100)),
                ('total_minutes', models.PositiveIntegerField(default=10000)),
                ('used_data', models.PositiveIntegerField(default=0)),
                ('used_minutes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=20)),
                ('data_allocation', models.PositiveIntegerField(default=0)),
                ('minute_allocation', models.PositiveIntegerField(default=0)),
                ('amount_due', models.PositiveIntegerField(default=0)),
                ('amount_paid', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('partial', 'Partial'), ('unpaid', 'Unpaid')], default='unpaid', max_length=10)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='dashboard.primaryline')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
