# Generated by Django 5.2.12 on 2026-04-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primaryline',
            name='plan',
            field=models.CharField(choices=[('WE Gold 525', 'WE Gold 525'), ('WE Gold 775', 'WE Gold 775'), ('WE Gold 1050', 'WE Gold 1050'), ('WE Gold 1300', 'WE Gold 1300'), ('WE Gold 2000', 'WE Gold 2000')], default='WE Gold 525', max_length=50),
        ),
        migrations.AlterField(
            model_name='primaryline',
            name='renewal_day',
            field=models.CharField(choices=[('1', 'Day 1'), ('16', 'Day 16')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='primaryline',
            name='total_data',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='primaryline',
            name='total_minutes',
            field=models.PositiveIntegerField(default=3700),
        ),
    ]
