# Generated by Copilot on 2026-04-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_primaryline_plan_alter_primaryline_renewal_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='primaryline',
            name='carryover_data',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='primaryline',
            name='carryover_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]