# Generated by Copilot on 2026-04-12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_primaryline_carryover_data_primaryline_carryover_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='primaryline',
            name='plan_cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AccountingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10)),
                ('title', models.CharField(max_length=120)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('entry_date', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True)),
                ('system_key', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-entry_date', '-id'],
            },
        ),
    ]