# Generated by Django 5.2.12 on 2026-05-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_primaryline_plan_cost_accountingentry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='amount_due',
            new_name='monthly_cost',
        ),
        migrations.RemoveField(
            model_name='member',
            name='amount_paid',
        ),
        migrations.AddField(
            model_name='member',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('paid', 'مدفوع'), ('unpaid', 'غير مدفوع')], default='unpaid', max_length=10),
        ),
        migrations.AlterField(
            model_name='primaryline',
            name='renewal_day',
            field=models.CharField(choices=[('1', 'DAY1'), ('16', 'DAY16')], default='1', max_length=20),
        ),
    ]
