# Generated by Django 5.2.12 on 2026-05-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_rename_amount_due_member_monthly_cost_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='notes',
            new_name='notes_text',
        ),
        migrations.AddField(
            model_name='member',
            name='note_type',
            field=models.CharField(blank=True, choices=[('delayed', 'مؤجل'), ('cash', 'دفع كاش'), ('free', 'مجاني'), ('relative', 'قريب'), ('custom', 'مخصص')], default='custom', max_length=20),
        ),
    ]
