# Generated by Django 5.2.12 on 2026-05-01 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_rename_notes_member_notes_text_member_note_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('delayed', 'مؤجل'), ('cash', 'دفع كاش'), ('free', 'مجاني'), ('relative', 'قريب'), ('custom', 'مخصص')], default='custom', max_length=20)),
                ('text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='dashboard.member')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
