# Generated by Django 5.2.12 on 2026-05-02 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_membernote'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('income', 'إيراد'), ('expense', 'مصروف')], max_length=10)),
                ('category', models.CharField(choices=[('automated', 'آلي'), ('manual', 'يدوي')], default='manual', max_length=10)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=255)),
                ('event_key', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('is_reversed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='dashboard.primaryline')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='dashboard.member')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
