# Generated by Django 5.2.12 on 2026-05-02 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_financialtransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('content', models.TextField(verbose_name='الوصف')),
                ('note_type', models.CharField(choices=[('reminder', 'تذكير'), ('collection', 'تحصيل'), ('expense', 'مصروف'), ('issue', 'مشكلة عميل'), ('followup', 'متابعة خط'), ('admin', 'إداري'), ('general', 'عام')], default='general', max_length=20, verbose_name='النوع')),
                ('priority', models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'عالي'), ('urgent', 'عاجل')], default='medium', max_length=20, verbose_name='الأولوية')),
                ('status', models.CharField(choices=[('active', 'نشطة'), ('completed', 'مكتملة'), ('archived', 'مؤرشفة')], default='active', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الاستحقاق')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='تثبيت')),
                ('related_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='global_notes', to='dashboard.primaryline', verbose_name='خط مرتبط')),
                ('related_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='global_notes', to='dashboard.member', verbose_name='فرد مرتبط')),
            ],
            options={
                'verbose_name': 'ملاحظة عامة',
                'verbose_name_plural': 'الملاحظات العامة',
                'ordering': ['-is_pinned', '-priority', '-created_at'],
            },
        ),
    ]
