# Generated by Django 5.2.12 on 2026-05-02 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_globalnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalnote',
            name='is_automated',
            field=models.BooleanField(default=False, verbose_name='تلقائي'),
        ),
    ]
